import type { Metadata } from "next";
import PolicyPage, { PolicyIdentity, PolicySection } from "@/components/PolicyPage";
import { STORE_POLICIES } from "@/data/store-policies";

export const metadata: Metadata = { title: "Privacidad | PulsoTech", description: "Cómo se usan los datos de pedidos y el almacenamiento del navegador en PulsoTech." };

export default function PrivacyPage() {
  return <PolicyPage title="Privacidad" intro="Aquí explicamos qué información se usa al navegar, coordinar una compra o solicitar atención." current="/privacidad/">
    <PolicySection title="1. Responsable y contacto"><PolicyIdentity /></PolicySection>
    <PolicySection title="2. Datos que puedes proporcionar"><p>Para coordinar una compra puedes indicar tu nombre, teléfono o cuenta de WhatsApp, dirección o punto de entrega, productos solicitados y datos necesarios para el pago o atención posterior. Si solicitas un comprobante, se requerirán los datos que correspondan. En consultas y reclamos recibimos la información que incluyas para identificar la compra y responderte.</p><p>Evita enviar contraseñas, claves bancarias o datos sensibles que no sean necesarios para tu solicitud. La tienda no pide datos de tarjetas desde su formulario de pedidos.</p></PolicySection>
    <PolicySection title="3. Para qué se utilizan"><p>Los datos se utilizan para responder consultas, confirmar disponibilidad, coordinar pagos y entregas, registrar ventas, atender garantías y reclamos y cumplir obligaciones aplicables. Proporcionar datos necesarios para una compra permite gestionar esa solicitud; si no los proporcionas, puede no ser posible coordinar la entrega o responderte.</p><p>No utilizamos los datos de un pedido para suscribirte automáticamente a publicidad. Cualquier finalidad adicional que requiera consentimiento deberá informarse y autorizarse por separado.</p></PolicySection>
    <PolicySection title="4. Servicios y destinatarios"><p>Al elegir enviar un pedido por WhatsApp, el mensaje y los datos que decidas enviar se comparten con ese servicio para coordinar la compra. El correo electrónico se utiliza para responder consultas. PulsoTech utiliza Supabase para el catálogo y los registros administrativos; el acceso a los datos de clientes está restringido al administrador autorizado.</p><p>El alojamiento web, los proveedores de correo y los servicios técnicos pueden procesar información de conexión, como la dirección IP. Estos servicios pueden operar fuera del Perú. Si se coordina transporte, solo se compartirán con quien realice la entrega los datos necesarios para efectuarla.</p></PolicySection>
    <PolicySection title="5. Almacenamiento del navegador y contenido externo"><p>La bolsa, favoritos, comparaciones y caché del catálogo se guardan en el navegador para mantener tus selecciones. Puedes eliminarlos desde la configuración del sitio en tu navegador. Los datos que escribes para coordinar un pedido se mantienen en el formulario y se incluyen en el mensaje cuando eliges enviarlo por WhatsApp.</p><p>El acceso administrativo utiliza almacenamiento de sesión y la verificación de Cloudflare Turnstile. Los videos de YouTube se cargan cuando eliges reproducirlos y pueden transmitir información al proveedor. Las imágenes externas y los enlaces a redes sociales también se rigen por las condiciones de sus respectivos servicios.</p></PolicySection>
    <PolicySection title="6. Conservación y seguridad"><p>Los registros se conservan durante el tiempo necesario para atender la compra, sus garantías, reclamos y obligaciones legales. Los mensajes enviados por WhatsApp o correo también pueden permanecer en esos servicios. Las solicitudes de eliminación se evaluarán teniendo en cuenta los registros que sea obligatorio conservar.</p><p>Las operaciones administrativas requieren una cuenta autorizada y doble verificación. Las políticas de acceso de la base de datos restringen los registros privados. Estas medidas reducen el riesgo de acceso no autorizado, aunque ninguna plataforma elimina todos los riesgos.</p></PolicySection>
    <PolicySection title="7. Tus derechos"><p>Puedes solicitar acceso, rectificación, cancelación u oposición al tratamiento de tus datos personales escribiendo a <a href={`mailto:${STORE_POLICIES.email}?subject=Solicitud%20sobre%20datos%20personales`} className="underline underline-offset-4 text-neutral-900 break-all">{STORE_POLICIES.email}</a>. Describe tu solicitud e indica cómo podemos identificar los datos a los que te refieres. Solo pediremos información adicional de identidad cuando sea necesaria para atenderla de forma segura.</p><p>También puedes acudir a la <a href="https://www.gob.pe/anpd" target="_blank" rel="noopener noreferrer" className="underline underline-offset-4 text-neutral-900">Autoridad Nacional de Protección de Datos Personales</a> para obtener información o ejercer las acciones que correspondan.</p></PolicySection>
  </PolicyPage>;
}
