import type { Metadata } from "next";
import PolicyPage, { PolicyIdentity, PolicySection } from "@/components/PolicyPage";
import { STORE_POLICIES } from "@/data/store-policies";

export const metadata: Metadata = { title: "Garantía, entregas y cambios | PulsoTech", description: "Condiciones de entrega local, atención de fallas y cambios voluntarios en PulsoTech." };

export default function DeliveryPolicyPage() {
  return <PolicyPage title="Garantía, entregas y cambios" intro="Lo que debes conocer antes de confirmar tu compra y cómo te atendemos después de recibirla." current="/garantia-y-entregas/">
    <PolicySection title="Entrega local en Chimbote"><p>Coordinamos por WhatsApp el lugar, fecha y horario de entrega. El costo de transporte, si corresponde, se informa antes de aceptar el pedido y se suma al precio de los productos para confirmar el total. La bolsa muestra el importe de los productos; el transporte se acuerda por separado.</p><p>La disponibilidad de un producto no implica entrega inmediata. Si necesitas recibirlo en una fecha concreta, consúltanos antes de confirmar. Ante un retraso, te contactaremos para acordar una nueva fecha o atender tu solicitud de cancelación.</p></PolicySection>
    <PolicySection title="Garantía de cada producto"><p>Antes de comprar te informaremos por escrito el plazo, cobertura y procedimiento de garantía aplicables al modelo elegido. PulsoTech recibe y atiende la solicitud del comprador, incluso cuando sea necesario gestionar una revisión con el proveedor. Una garantía comercial complementa los derechos que te reconoce la legislación peruana.</p><p>Si el producto presenta una falla, no corresponde a lo ofrecido o llega con daños, comunícate con nosotros indicando el pedido y describiendo el problema. Podemos solicitar fotos o un video para orientar la evaluación. Según corresponda, se atenderá mediante reparación, reposición o devolución del importe.</p><p>No exigimos que la caja permanezca sellada para atender una falla descubierta al abrir o probar el producto. Tampoco condicionamos la atención a que hayas grabado un video del desembalaje.</p></PolicySection>
    <PolicySection title={`Cambios voluntarios dentro de ${STORE_POLICIES.voluntaryChangeDays} días`}><p>Si cambias de preferencia, puedes solicitar un cambio dentro de los {STORE_POLICIES.voluntaryChangeDays} días calendario siguientes a la entrega, siempre que el producto esté sin abrir, sin usar, con sus sellos intactos y con todos sus accesorios y empaque. La solicitud debe permitir identificar la compra.</p><p>El cambio está sujeto a la disponibilidad del modelo elegido. Informaremos cualquier diferencia de precio y costo de transporte antes de que lo aceptes. Estos cambios por preferencia no incluyen una devolución automática de dinero y son independientes de la atención de defectos o incumplimientos.</p></PolicySection>
    <PolicySection title="Cómo solicitar atención"><p>Indica el número de pedido o los datos que permitan identificar la compra, el modelo y una explicación del problema o cambio solicitado. Revisaremos contigo el procedimiento y, si hace falta, la entrega del producto para evaluarlo.</p><PolicyIdentity /></PolicySection>
  </PolicyPage>;
}
